### ISSUE TITLE
question about the dynamic threshold

### ISSUE THREAD

**Issue by jlro001** [khundman/telemanom#20]
How did you come up with the calculating of the dynamic threshold?
Is it enlightened by other works?
Can you please kindly explain it?

**Comment by vc1492a** [comment]
@jlro001 thanks for the comment. You can find more information on how the dynamic threshold is set (briefly) in the video and (in detail) within the publication posted [on the KDD website](https://www.kdd.org/kdd2018/accepted-papers/view/detecting-spacecraft-anomalies-using-lstms-and-nonparametric-dynamic-thresh).

**Comment by khundman** [comment]
@jlro001 It was motivated by the fact that the residuals were non-Gaussian and a nonparametric approach allows for better generalization to other domains and datasets (with some tuning). Without too much overhead, all data points are scored in relation to the other data points, rather than relying on a distribution that doesn't fit the data to score each point. I haven't seen the approach in other works.

**Comment by jlro001** [comment]
Firstly, thank u for responding. 
Actually, my question is how you come up with the complex formula to determine the number of standard deviations above μ. 
Are there some works related to this？
Thank u!

**Comment by khundman** [comment]
None that I'm aware of. I created it to try and balance the empirical issues I was seeing (as described in the paper).
