### ISSUE TITLE
Normalisation of test and training data

### ISSUE THREAD

**Issue by plankthom** [khundman/telemanom#23]
First, many thanks for your insightful work ...

I however have an issue when loading the training and test data sets: in most cases they seem to be normalised to [-1,1] independently, and I was wondering whether this would not make the trained model inaccurate.

Eg. a density plot for the channel `E4` : 
![distplot-E-4](https://user-images.githubusercontent.com/1620679/59519752-dcc4d000-8ec8-11e9-936e-9c9bfe4d0169.png)

Or did i miss something else?

**Comment by khundman** [comment]
Thanks for the comment, I'm looking into this. This was an issue I had found before releasing the data and thought was corrected. If there are other suspicious channels you have noticed it would be helpful if you could provide them. 

This one looks like what you have described, but there are instances where channel behavior can change abruptly due to commanding. I will follow up.

**Comment by khundman** [comment]
@plankthom Following up on this - it is an error that won't be corrected. Unfortunately I no longer have access to the raw data and therefore can't rescale. I don't think it is material to the results or methods (in a sense it actually demonstrates the robustness of the overall approach). Thanks again for the note.

**Comment by mistycheney** [comment]
Is it possible to provide the list of sequences that are confirmed to have this issue, so we can exclude them from our experiments?
