### ISSUE TITLE
Question about n_predictions

### ISSUE THREAD

**Issue by edf42001** [khundman/telemanom#24]
Hello,

I was wondering the purpose of the n_prediction config value. First, in your paper you mention that you could predict one time step ahead, or more than one. Currently, n_predictions in your config file is set to 10, and your model predicts 10 steps ahead. However, in the predict_in_batches method it looks like you ignore all those predictions except for the first one, effectivley only predicting one step ahead again. https://github.com/khundman/telemanom/blob/8eab60bd5de0c1bbfaf9888e07ea172b7466a0b1/telemanom/modeling.py#L111. I was wondering if I am understanding this right or if I am missing something.

**Comment by khundman** [comment]
Yes, your understanding is correct. The 10 predictions are generated with the assumption that forcing the model to predict further into the future will encourage better predictions in the short term (one step ahead in this case) since the loss will be calculated for all ten predictions and will be used during training. Often times if you are only forecasting one step ahead, the model will tend to use the last available value as the prediction. This approach encourages real learning, even though we are only utilizing the first prediction after the fact.

**Comment by edf42001** [comment]
Ok, thanks! That makes sense.
