### ISSUE TITLE
Issues with run.py

### ISSUE THREAD

**Issue by matmil1997** [khundman/telemanom#4]
Hi,

I'm having a few issues with this repo (I cloned the no-labels branch for unsupervised learning).

- I tried to run `run.py` in my IDE (Spyder downloaded via Anaconda) but am given the error `ModuleNotFoundError: No module named 'telemanom._globals'`, yet I can run the script in my Anaconda Prompt. 

- When I do run `run.py` in the prompt, only 76/85 of the channels seem to be processed. For instance, the issue I get with T-11 is
`Chan: T-11 (76 of 85)
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    run(config, _id, logger)
  File "run.py", line 51, in run
    X_train, y_train, X_test, y_test = helpers.load_data(anom)
  File "C:\...\telemanom\telemanom\helpers.py", line 83, in load_data
    X_test, y_test = shape_data(test, train=False)
  File "C:\...\telemanom\telemanom\helpers.py", line 110, in shape_dat
a
    data = data[:, :]
IndexError: too many indices for array`

- Regarding the above line of code (`data = data[:,:]`) in `helpers.py`, I was wondering what the purpose of it is? It seems to just reassign `data` to itself and ensure it two-dimensional. 

- Lastly, after executing `run.py` the average channel seems to take on average about 45 s. This leads to an accumulated processing time of around 45 min every time I try to make a change to the script to get it working. Is this normal?

Thank you in advance!

**Comment by khundman** [comment]
Hi @matmil1997,

Answering your bullets in order:

- When you run in the Spyder IDE make sure you working directory is set to be `The directory of the file being executed` as the filepaths are all relative to the root of the repo:

![image](https://user-images.githubusercontent.com/5148804/43693447-b5b3de2a-98e2-11e8-9cec-67261310a2eb.png)

- The provided data was intended to be run with the `master` branch (since it comes with labels), and the `no-labels` branch is intended to be run with data that doesn't have labels (user-provided data). You are getting this error because I left a few extra channels in the provided data that don't have enough test data. These are skipped when processing with the `master` branch but the `no-labels` branch tried to process them. I have cleaned these out of so you can use the provided data with either branch. 

- This was a check to ensure enough test data was available for a given channel (`data` will only be 1D if insufficient data), but its purpose isn't clear. I've changed it to an assertion to be more explicit.

- In the `run()` function in `run.py` there is a `for` loop that iterates through a list of channels called `chans`, if you don't want to process all channels each time, you can alter this list to process a subset. There are also options in `config.yaml` that allow you to specify if you want to train a new model each time or generate new predictions each time, which will alter processing times depending on what you are trying to do.

**Comment by khundman** [comment]
Fixed, thanks!

**Comment by matmil1997** [comment]
Everything seems to work now, thanks!
