### ISSUE TITLE
Sliding window dynamic thresholding behaviour

### ISSUE THREAD

**Issue by meliksahturker** [khundman/telemanom#51]
![thumbnail_image001](https://user-images.githubusercontent.com/67103746/102046665-cca6ed00-3dec-11eb-8878-ba072e472f44.png)
In this figure, x axis is time, y axis is error(abs(y - yhat)) and blue line is the threshold drawn by the dynamic threshold algorithm. Ignore the first 1000 data points since I simply apply 6 sigma (z=6) until data is accumulated.

I am applying dynamic thresholding without pruning to streaming data with sliding the window for each new data that arrives. My window size is 1000 therefore it always calculates the threshold by looking at last 1000 errors. I have two questions, one of which is the issue.

1- Whenever a very high error(anomaly) is introduced a peak is observed for a **single** timestep and it drops. In the end the threshold is increased and this is the expected behavior but is it expected to see a peak that lasts 1 time step? See around timestep 1200 for example.

2- This is the reason I am posting: Whenever an anomaly is leaving the window, being 1000 timesteps behind, again a similar peak occurs. See around timestep 2200, and any 1000 timestep after an anomaly. This is the real oddness. Is it normal? If so what is the justification, I could not figure it out.

Having witnessed this odd behavior, what is the best/proper practice to use dynamic thresholding? Should I simply not calculate it in each timestep but this would defeat the purpose.

**Comment by khundman** [comment]
Hi @meliksahturker thanks for the thoughtful questions.

What you are seeing is expected behavior. At the end of section 3.2 in the paper, it states:

"In simple terms, a threshold is found that, if all values above are removed, would cause the greatest percent decrease in the mean and standard deviation of the smoothed errors. The function also penalizes for having larger numbers of anomalous values and sequences to prevent overly greedy behavior."

This piece is fundamental to answering your questions. 

For question [1], the situations where you see the threshold peak and then drop, it is because the thresholding algorithm found a new optimal tradeoff between the competing forces described in the excerpt above. The abrupt drop in threshold occurs when other secondary spikes occur near the large ones and the thresholding algorithm "decides" to additionally include those as potential anomalies (to be further pruned downstream). The dynamic thresholding can be thought of as constantly searching for the best "cuts" where there aren't too many points above the threshold but the ones that are, if removed, would significantly drop the mean and st. dev. of the sequence.

For question [2], this is explained by the prior anomaly dropping out of the back of the sequence. The standard deviation used to initialize the threshold is 12 ([link](https://github.com/khundman/telemanom/blob/master/telemanom/errors.py#L241)) , and if no useful threshold can be found that meets basic "guardrail" criteria ([link](https://github.com/khundman/telemanom/blob/master/telemanom/errors.py#L313)) the threshold will remain at 12 st. devs above the mean to safely avoid false positives. So when you see the threshold jump, no good "cuts" or thresholds can be found that don't result in an unrealistically large number of anomalous sequences/points in the sequence. Prior to the jump, when the anomaly was still in the sequence, a good "cut" was found that classified that anomaly as such (and only that anomaly).
